In [11]:
import numpy as np
import random

# 환경 설정 (5x5 그리드)
grid_size = 5
goal_state = (4, 4)  # 목표 위치
trap_state = (2, 2)  # 함정 위치
actions = ['up', 'down', 'left', 'right']
action_dict = {'up': (-1, 0), 'down': (1, 0), 'left': (0, -1), 'right': (0, 1)}

# Q-table 초기화
Q_table = np.zeros((grid_size, grid_size, len(actions)))

# 하이퍼파라미터 설정
alpha = 0.1  # 학습률
gamma = 0.9  # 감가율 (미래 보상에 대한 할인)
epsilon = 0.1  # 탐험 비율 (exploration)

# 보상 함수
def get_reward(state):
    if state == goal_state:
        return 100  # 목표에 도달하면 보상
    elif state == trap_state:
        return -100  # 함정에 빠지면 큰 패널티
    else:
        return -1  # 나머지 이동에는 작은 패널티

# 다음 상태를 얻는 함수
def get_next_state(state, action):
    move = action_dict[action]
    next_state = (state[0] + move[0], state[1] + move[1])

    # 그리드 바깥으로 나가는 움직임은 무시 (벽에 부딪히면 같은 자리 유지)
    if next_state[0] < 0 or next_state[0] >= grid_size or next_state[1] < 0 or next_state[1] >= grid_size:
        next_state = state
    return next_state

# 행동을 선택하는 함수 (탐험과 활용 중 선택)
def choose_action(state):
    if random.uniform(0, 1) < epsilon:
        return random.choice(actions)  # 탐험: 무작위 선택
    else:
        state_index = state[0], state[1]
        return actions[np.argmax(Q_table[state_index])]  # 활용: Q-value가 가장 큰 행동 선택

# Q-learning 알고리즘 실행
def q_learning(episodes):
    for episode in range(episodes):
        state = (0, 0)  # 시작 위치
        done = False

        while not done:
            action = choose_action(state)
            next_state = get_next_state(state, action)
            reward = get_reward(next_state)

            state_index = state[0], state[1]
            next_state_index = next_state[0], next_state[1]
            action_index = actions.index(action)

            # Q-learning 업데이트 공식
            Q_table[state_index][action_index] = Q_table[state_index][action_index] + \
                alpha * (reward + gamma * np.max(Q_table[next_state_index]) - Q_table[state_index][action_index])

            # 목표에 도달하면 종료
            if next_state == goal_state or next_state == trap_state:
                done = True

            state = next_state

# Q-learning 실행
q_learning(500)

# 학습된 Q-table 출력
print("Q-table:")
print(Q_table)


Q-table:
[[[ 26.94180689  42.612659    30.75921187  13.34597853]
  [ -1.73141695   3.32151981  -1.79956809  37.79404055]
  [  7.395012    53.35059281  -1.25858501  -1.16201057]
  [ -0.8621761   39.76863464   2.6864676    3.24807926]
  [ -0.58519851  61.52281152  -0.62398846  -0.58519851]]

 [[ 14.25229012   0.9831327   30.61005826  48.45851   ]
  [ 13.34945435   9.43965615  27.16791261  54.9539    ]
  [ 21.95158949 -65.13215599  36.8180588   62.171     ]
  [ 14.38118559  45.46150283  34.66659367  70.19      ]
  [ 36.30917252  79.1         41.69624565  47.92876697]]

 [[  3.1392      -1.18603836  -1.20689408  10.78352274]
  [ 37.0959491    3.25532449  -0.92425412 -34.39      ]
  [  0.           0.           0.           0.        ]
  [ -0.2071       6.3169101  -27.1         73.44848792]
  [ 55.45372704  89.          29.08637991  39.62580013]]

 [[ -0.76078789  -0.79042501  -0.86040151   0.46641213]
  [ -0.46615316  -0.54973899  -0.68359006  12.81023058]
  [-19.          -0.22249     -0.

In [13]:
import numpy as np
import random

# 환경 설정 (4x4 그리드 맵)
grid_size = 4
goal_state = (3, 3)  # 목표 지점
actions = ['up', 'down', 'left', 'right']  # 가능한 행동

# Q 테이블 초기화
q_table = np.zeros((grid_size, grid_size, len(actions)))

# 하이퍼파라미터 설정
alpha = 0.1   # 학습률
gamma = 0.9   # 할인율
epsilon = 0.1  # 탐험-이용 균형을 위한 탐험 확률
num_episodes = 1000

# 환경에서의 보상 함수
def get_reward(state):
    if state == goal_state:
        return 10  # 목표 지점에 도달하면 보상 10
    else:
        return -1  # 그 외에는 -1의 보상

# 상태에서 가능한 행동을 실행한 후 새로운 상태 반환
def take_action(state, action):
    row, col = state
    if action == 'up' and row > 0:
        row -= 1
    elif action == 'down' and row < grid_size - 1:
        row += 1
    elif action == 'left' and col > 0:
        col -= 1
    elif action == 'right' and col < grid_size - 1:
        col += 1
    return (row, col)

# 탐험-이용 정책 (epsilon-greedy)
def choose_action(state):
    if random.uniform(0, 1) < epsilon:
        return random.choice(actions)  # 탐험
    else:
        row, col = state
        return actions[np.argmax(q_table[row, col])]  # 이용 (Q-값이 가장 큰 행동 선택)

# 학습 과정
for episode in range(num_episodes):
    state = (0, 0)  # 시작 지점
    done = False

    while not done:
        # 현재 상태에서 행동 선택
        action = choose_action(state)

        # 선택한 행동으로 새로운 상태로 이동
        new_state = take_action(state, action)

        # 보상 계산
        reward = get_reward(new_state)

        # Q 테이블 업데이트
        row, col = state
        new_row, new_col = new_state
        action_idx = actions.index(action)

        # Q-값 업데이트 식
        q_table[row, col, action_idx] = q_table[row, col, action_idx] + alpha * (
            reward + gamma * np.max(q_table[new_row, new_col]) - q_table[row, col, action_idx]
        )

        # 상태 업데이트
        state = new_state

        # 목표 상태에 도달했을 때 에피소드 종료
        if state == goal_state:
            done = True

# 최종 Q 테이블 출력
print("최종 Q 테이블:")
print(q_table)

# 학습된 경로 출력
def print_optimal_path():
    state = (0, 0)
    path = [state]

    while state != goal_state:
        row, col = state
        action_idx = np.argmax(q_table[row, col])
        action = actions[action_idx]
        state = take_action(state, action)
        path.append(state)

    print("학습된 최적 경로: ", path)

print_optimal_path()


최종 Q 테이블:
[[[ 0.34283889  1.8098      0.52786617  1.37788788]
  [-0.87493526  3.10155911 -1.29920996 -0.97355433]
  [-0.76961055  3.16685724 -0.80913958 -0.68817463]
  [-0.3940399  -0.36983307 -0.43255959 -0.3940399 ]]

 [[ 0.39653504  1.58777823  1.57672725  3.122     ]
  [ 1.35251514  4.21596246  1.6413292   4.58      ]
  [ 0.362944    6.2         2.94540726  4.17984369]
  [-0.31112174  7.36859804  0.25450291  0.30381558]]

 [[-0.5193152  -0.68956306 -0.67934652  4.0611062 ]
  [ 1.23772704 -0.36507438 -0.01358933  6.19744088]
  [ 3.98823031  8.          4.02507395  7.36535533]
  [ 1.1102606   9.97781469  1.178       1.15801877]]

 [[-0.41647852 -0.3940399  -0.3940399  -0.30174854]
  [ 0.2342103   0.37316844 -0.21601     7.67604206]
  [ 5.63129382  7.71166852  5.00592336 10.        ]
  [ 0.          0.          0.          0.        ]]]
학습된 최적 경로:  [(0, 0), (1, 0), (1, 1), (1, 2), (2, 2), (3, 2), (3, 3)]


In [7]:
import gym
import numpy as np
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

# 간단한 그리드 환경 만들기
class GridEnv(gym.Env):
    def __init__(self):
        super(GridEnv, self).__init__()
        self.grid_size = 4
        self.action_space = gym.spaces.Discrete(4)  # 상, 하, 좌, 우
        self.observation_space = gym.spaces.Box(low=0, high=self.grid_size-1, shape=(2,), dtype=np.int32)
        self.state = np.array([0, 0])  # 시작 지점
        self.goal_state = np.array([3, 3])

    def reset(self):
        self.state = np.array([0, 0])
        return self.state

    def step(self, action):
        row, col = self.state
        if action == 0 and row > 0:
            row -= 1
        elif action == 1 and row < self.grid_size - 1:
            row += 1
        elif action == 2 and col > 0:
            col -= 1
        elif action == 3 and col < self.grid_size - 1:
            col += 1
        self.state = np.array([row, col])

        # 보상 계산
        done = np.array_equal(self.state, self.goal_state)
        reward = 10 if done else -1

        return self.state, reward, done, {}

    def render(self, mode='human'):
        grid = np.zeros((self.grid_size, self.grid_size))
        grid[tuple(self.state)] = 1
        grid[tuple(self.goal_state)] = 2
        print(grid)

# 환경 만들기
env = DummyVecEnv([lambda: GridEnv()])

# PPO 에이전트 학습
model = PPO('MlpPolicy', env, verbose=1)
model.learn(total_timesteps=10000)

# 최적 경로 출력
obs = env.reset()
done = False
path = [obs]

while not done:
    action, _ = model.predict(obs)
    obs, reward, done, _ = env.step(action)
    path.append(obs)

print("학습된 최적 경로: ", path)


/usr/local/lib/python3.10/dist-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


Using cpu device
-----------------------------
| time/              |      |
|    fps             | 728  |
|    iterations      | 1    |
|    time_elapsed    | 2    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 671         |
|    iterations           | 2           |
|    time_elapsed         | 6           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.013489812 |
|    clip_fraction        | 0.175       |
|    clip_range           | 0.2         |
|    entropy_loss         | -1.37       |
|    explained_variance   | -0.00861    |
|    learning_rate        | 0.0003      |
|    loss                 | 36.1        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0261     |
|    value_loss           | 98.4        |
-----------------------------------------
-----------------